### ISSUE TITLE
Countdown timer is a little too verbose

### ISSUE THREAD

**Issue by dpetzel** [test-kitchen/kitchen-openstack#113]
I appreciate the message letting me know its going to sleep for a bit, but the second refresh on the count down timer is a little verbose. This is cluttering up CI logs. Thoughts on removing this, or at the very least pushing it to debug level?
```
Sleeping for 90 seconds to let your server to start up...
       01:30
       01:29
       01:28
       01:27
       01:26
       01:25
       01:24
....
```

**Comment by jjasghar** [comment]
So suprisingly this has been harder to convert to "." then i thought. But yeah i get what you're saying and I'm working on it.

**Comment by jjasghar** [comment]
https://github.com/test-kitchen/kitchen-openstack/pull/115 Thoughts @dpetzel ?

**Comment by dpetzel** [comment]
I like it.

**Comment by jjasghar** [comment]
Awesome, I'll get another pre release pushed here in a bit.
