### ISSUE TITLE
Put the yml files for each instance in .kitchen/kitchen-openstack

### ISSUE THREAD

**Issue by miroswan** [test-kitchen/kitchen-openstack#116]
It is less likely that there will be a collision of file namespace across drivers if the files live in their own directory under .kitchen. Less of a bug and more of an idea to prevent future problems.

**Comment by jjasghar** [comment]
This seems like a good idea. But i think this needs higher up the stack and get test-kitchen proper involved. 

/cc @tyler-ball @fnichol

**Comment by miroswan** [comment]
I think the vagrant driver puts its files under .kitchen/kitchen-vagrant if I remember correctly. But yeah, I'd be interested on their input.

**Comment by jjasghar** [comment]
Closed due to no response, this should be opened in test-kitchen/test-kitchen.
