### ISSUE TITLE
Glance Caching sleep time should probably be a configurable option

### ISSUE THREAD

**Issue by carpnick** [test-kitchen/kitchen-openstack#117]
[This line](https://github.com/test-kitchen/kitchen-openstack/blob/master/lib/kitchen/driver/openstack.rb#L100) should be configurable. 

Linux images are fine with that requirement.  But Windows images, we have seen go much higher with 15-18 GB images.

**Comment by jjasghar** [comment]
[wait for server](https://github.com/test-kitchen/kitchen-openstack/blob/master/lib/kitchen/driver/openstack.rb#L397) doesn't do what you want?

**Comment by carpnick** [comment]
Figured that was for a different use case.  If it's the same use case, maybe we should consider removing the random 30 second wait?  Then default the wait_for_server to be 30 via configurable option?

**Comment by jjasghar** [comment]
Nope, the "sleep 30" is due to a caching issue that glance has. Yep, it's gross, but it's the only way we've been able to figure out how to get around it.

It's literally called `glance_cache_`something or something. I'm not recalling the name at the moment unfortunately.

**Comment by carpnick** [comment]
Right so the cache issue is due to image download to the DS, correct?  Basically what I am wondering is, what if we have a bigger image?  Your first comment appeared to say use wait_for_server, but this call happens after the floating ip call.

**Comment by carpnick** [comment]
Another option that we implemented, that we could do a PR, we waited for the VM state to change to ready.

Something like this: `server.wait_for(600) { print ".";ready? }`

**Comment by jjasghar** [comment]
I've put the PR in, please take a look, suggestions are more then welcome.
