### ISSUE TITLE
provision_command

### ISSUE THREAD

**Issue by equick** [test-kitchen/kitchen-openstack#118]
This may be a failure in my understanding in how this works so apologies in advance if I've got this wrong but I noticed that kitchen-docker has a directive called provision_command and wondered if the same functionality could be added to kitchen-openstack?

https://github.com/portertech/kitchen-docker#provision_command

The reason for asking is that I have run into an issue where installing a package requires a group/user to be configured first.

I can get round it using https://docs.chef.io/ctl_kitchen.html#kitchen-exec for now

**Comment by jjasghar** [comment]
Interesting. I'll have to look into this, but yeah, this probably be adventitious to have in `kitchen-openstack`.

I'll put it as a feature request.

**Comment by dpetzel** [comment]
Wouldn't this just be handled via userdata?

**Comment by jjasghar** [comment]
@dpetzel that's actually a good option to make that happen. Maybe we should put some doc's around leveraging the `cloud_init` stuff on boot?

**Comment by dpetzel** [comment]
I'd try to avoid "re-documenting" cloud-init, but certainly a mention with a link wouldn't hurt.

**Comment by dpetzel** [comment]
In fact, it appears userdata isn't documented at all, and I recall now I had to do some code trolling the first time around to figure out this driver supported it.

**Comment by jjasghar** [comment]
:metal: thanks @dpetzel !

**Comment by equick** [comment]
Thanks @dpetzel. Could you show me an example of how to use this please?

**Comment by dpetzel** [comment]
Sure, something like this:

```
# .kitchen.yml snippet
  - name: rhel6
    driver_config:
      image_ref: your-image
      flavor_ref: your_flavor
      user_data: userdata.txt    # <--------
```

Then create a `userdata.txt` in the same directory as your .kitchen.yml
```
#!/bin/sh
echo "do whatever you want to pre-configure your machine"
```

**Comment by equick** [comment]
Thanks again @dpetzel. For some reason it doesn't work in my case although the kitchen create succeeds. Does my [.kitchen.yml](https://gist.github.com/equick/da7851b0ebfa58097485) look ok to you?

This is my `userdata.txt`

```
bash-4.1$ ls -l userdata.txt
-rw-r--r-- 1 jenkins jenkins 163 Oct 28 13:27 userdata.txt

bash-4.1$ cat userdata.txt
#!/bin/sh

echo "Provisioning"
/usr/sbin/groupadd test
/usr/sbin/useradd -g test test
```

**Comment by dpetzel** [comment]
It does look about right. Do you know if the images you are using have cloud-init installed? Its possible (albeit I think unusual) that your images are not configured to take advantage of userdata. This is discussed here http://docs.openstack.org/image-guide/content/ch_openstack_images.html

**Comment by jjasghar** [comment]
@dpetzel that above looks more or less on what we need to add to the README, do you want to put the PR in or do you want me to make it happen?

**Comment by dpetzel** [comment]
Feel free to add it if your in there.

**Comment by jjasghar** [comment]
https://github.com/test-kitchen/kitchen-openstack/pull/121

**Comment by equick** [comment]
Thanks for updating the docs.
cloud-init was not installed so getting that fixed now and will test again.

**Comment by jjasghar** [comment]
Going ahead and closing this issue. Going to push people towards using `user_data`. :metal:
