### ISSUE TITLE
Boot from Image (into new volume)

### ISSUE THREAD

**Issue by styk-tv** [test-kitchen/kitchen-openstack#130]
Quick question: Any way to boot from image into new volume which is possible in OpenStack? You're already allowing boot of new volume from snapshot, probably small step to allow boot new volume from image? Or have I missed something in Doc?

Cheers.

Different from https://github.com/test-kitchen/kitchen-openstack/issues/75

**Comment by jjasghar** [comment]
> A new volume from an image. 
I'm sorry, but I don't fully understand this statement. How is this different than just using the standard way the image is pulled from glance and bootstrapped?
If you have a way to create a new volume then inject the OS from an image into the volume i think that's pretty specific to your OpenStack cloud.
Unless I'm miss understanding you, can you send me some documentation on this?

**Comment by BBK-PiJ-2015-14** [comment]
I don't think this is any extra ordinary. You either use Glance and local cache or Cinder Volume to host your instance. Working with windows is a little tricky with base updated sys-prepped images at 50GB. Either way workflow is to have a QCOW2 image in Glance and then at boot automatically create new volume (from glance to cinder) and attach new volume to new instance and boot, then run some tests, then destroy the instance and volume to make room for next test.

I'm running OpenStack Kilo (Nova 12) RDO out of the box and without modifications. This workflow is possible using single line nova boot command by specifying source image then destination volume size.

nova boot --flavor FLAVOR --block-device \
  source=SOURCE,id=ID,dest=DEST,size=SIZE,shutdown=PRESERVE,bootindex=INDEX \
  NAME

REF 3: http://docs.openstack.org/user-guide/cli_nova_launch_instance_from_volume.html

or using dashboard

![instance-create](https://cloud.githubusercontent.com/assets/14973860/11700258/b3730ea2-9ec0-11e5-952e-05d9d00aa41c.png)

**Comment by jjasghar** [comment]
After some research this would require a TON of work. The driver is designed for ephemeral disks and not boot off of Cinder Volumes. Granted there is support for it, but my cloud doesnt have a way to test this. 

I'm going to close this for now, we can reopen it in the future if there is more interest around it.
