### ISSUE TITLE
Support Identity v3

### ISSUE THREAD

**Issue by stenstad** [test-kitchen/kitchen-openstack#137]
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Fog seems to have implemented support for Openstack Identity v3 a while ago, but I think the auth logic in kitchen needs to be updated to use the new codepath.

Would it be possible to add support for Identity v3?

**Comment by jjasghar** [comment]
Hi! 

If you look at the https://github.com/test-kitchen/kitchen-openstack#minimum-configuration you'll see that we do have support for v3. Maybe we should update the examples? How would you suggest to make that more clear?

**Comment by jjasghar** [comment]
@stenstad any chance you've followed up on this?

**Comment by jjasghar** [comment]
@stenstad bump.

**Comment by stenstad** [comment]
Sorry, I never did follow up. But as far as I can see you are totally right, it is pretty clear in the Readme now.

**Comment by jjasghar** [comment]
:metal:
