### ISSUE TITLE
ssh_key: how to?

### ISSUE THREAD

**Issue by gvenka008c** [test-kitchen/kitchen-openstack#138]
Hi,

I have the id_rsa in the path where the .kitchen.yml resides. When I run the 

#kitchen converge default-mesos
[SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@xx.xxx.xxx.xxx>)
 [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@xx.xxx.xxx.xxx>)

Here is snipped from .kitchen.yml file. I was able to converge but not able to login to the openstack machine using kitchenci. Can you please suggest?

transport:
  ssh_key: /path/id_rsa
  connection_timeout: 10
  connection_retries: 5
  username: clduser

**Comment by jjasghar** [comment]
You need to have some spaces under that transport section.

```yml
transport:
   ssh_key: /path/id_rsa
```

**Comment by gvenka008c** [comment]
@jjasghar There is a space. The copy and pasted into github removed it. Here is the snippet again. id_rsa is in my current directory where I run the kitchen converge command.

transport:
  ssh_key: id_rsa
  connection_timeout: 10
  connection_retries: 5
  username: clduser

**Comment by gvenka008c** [comment]
@jjasghar Here is the log

I, [2016-02-22T19:15:56.704496 #47754]  INFO -- default-mesos: [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@96.119.242.102>)
I, [2016-02-22T19:15:58.541726 #47754]  INFO -- default-mesos: [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@96.119.242.102>)
I, [2016-02-22T19:16:00.371747 #47754]  INFO -- default-mesos: [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@96.119.242.102>)
I, [2016-02-22T19:16:02.227180 #47754]  INFO -- default-mesos: [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@96.119.242.102>)
W, [2016-02-22T19:16:04.048887 #47754]  WARN -- default-mesos: [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user clduser@96.119.242.102>)
E, [2016-02-22T19:16:04.051071 #47754] ERROR -- default-mesos: Converge failed on instance <default-mesos>.
E, [2016-02-22T19:16:04.051157 #47754] ERROR -- default-mesos: ------Exception-------
E, [2016-02-22T19:16:04.051179 #47754] ERROR -- default-mesos: Class: Kitchen::ActionFailed
E, [2016-02-22T19:16:04.051196 #47754] ERROR -- default-mesos: Message: SSH session could not be established
E, [2016-02-22T19:16:04.051210 #47754] ERROR -- default-mesos: ---Nested Exception---
E, [2016-02-22T19:16:04.051224 #47754] ERROR -- default-mesos: Class: Kitchen::Transport::SshFailed
E, [2016-02-22T19:16:04.051238 #47754] ERROR -- default-mesos: Message: SSH session could not be established
E, [2016-02-22T19:16:04.051262 #47754] ERROR -- default-mesos: ------Backtrace-------
E, [2016-02-22T19:16:04.051278 #47754] ERROR -- default-mesos: /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.5.0/lib/kitchen/provisioner/base.rb:76:in `rescue in call'
E, [2016-02-22T19:16:04.051293 #47754] ERROR -- default-mesos: /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.5.0/lib/kitchen/provisioner/base.rb:79:in `call'
E, [2016-02-22T19:16:04.051306 #47754] ERROR -- default-mesos: /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:373:in `block in converge_action'
E, [2016-02-22T19:16:04.051320 #47754] ERROR -- default-mesos: /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `call'

**Comment by gvenka008c** [comment]
@jjasghar There was a file in .kitchen folder which had been using my key. I changed it to the clduser key and it worked.

**Comment by jjasghar** [comment]
Good to hear that you got this resolved.
