### ISSUE TITLE
kitchen-openstack should use SSH Agent

### ISSUE THREAD

**Issue by andrey01** [test-kitchen/kitchen-openstack#149]
It would be good to see if kitchen-openstack driver could leverage the SSH Agent so that it won't be necessary to copy the private ssh key to the server.

It also complains when the private key is missing ~/.ssh/id_* .

**Comment by andrey01** [comment]
Sorry, seems it is working fine with 3.1.0.
However it still complains when the key is missing ~/.ssh/id_*  which is normal when using the SSH Agent.

**Comment by jjasghar** [comment]
You can change it via: https://github.com/test-kitchen/kitchen-openstack#private_key_path or https://github.com/test-kitchen/kitchen-openstack#public_key_path
