### ISSUE TITLE
Enhancement: generate openstack keypair on create

### ISSUE THREAD

**Issue by andrey01** [test-kitchen/kitchen-openstack#150]
It would be a good idea for kitchen-openstack driver to generate a temporary openstack keypair used for instance creation and remove it on kitchen destroy.

**Comment by jjasghar** [comment]
This would require a creation of a new tenant and quite a bit of engineering. It sounds great, and I'd love to see someone put the time in for this, but it's out of scope for basic usage.

Thanks for the suggestion though!
