### ISSUE TITLE
Is there a way to re-use volume?

### ISSUE THREAD

**Issue by guskovd** [test-kitchen/kitchen-openstack#181]
For example, I want to re-use the volume after kitchen destroy.

**Comment by jjasghar** [comment]
Sorry this is not really in scope. The idea is that when you run the `kitchen destroy` it destroy's everything. You could _in_theory_ leverage: https://github.com/test-kitchen/kitchen-openstack/blob/master/README.md#disk-configuration this to do it, but that requires your OpenStack cloud to be compatible.

**Comment by guskovd** [comment]
This is somehow strange. In my opinion, volume is precisely the mechanism that implements an invariant with respect to instances
I have an idea how to implement this.

**Comment by guskovd** [comment]
I do not actively use the volumes in openstack.
But my idea for docker users should be obvious.
Volumes - this is something that does not change and contains some kind of constant information
