### ISSUE TITLE
Support the latest version of Chef DK

### ISSUE THREAD

**Issue by Lasering** [test-kitchen/kitchen-openstack#197]
The latest version of kitchen-openstack 3.6.2 does not work with:

Chef Development Kit Version: 4.0.60
kitchen version: 2.2.5

**Comment by mrmarbury** [comment]
make this the latest version of chef-workstation as well. There is already this [PR 195](https://github.com/test-kitchen/kitchen-openstack/pull/195) which includes the necessary change. It is failed but not because of the change. So somebody please merge this in. Thx

**Comment by ramereth** [comment]
This was resolved in #195
