### ISSUE TITLE
Unrecognized argument error from fog

### ISSUE THREAD

**Issue by pdohertybcov** [test-kitchen/kitchen-openstack#205]
I'm using Keystone v2, and an older version of Openstack (Liberty.  Yes, I know it's old)

Since upgrading to kitchen-openstack 5.0.0 I get this warning when doing just about anything that involves the kitchen-openstack gem:
```
[fog][WARNING] Unrecognized arguments: provider
```
It often appears multiple times, presumably during each API call to Openstack.

I tracked it down to this line of code:
https://github.com/test-kitchen/kitchen-openstack/blob/v5.0.0/lib/kitchen/driver/openstack.rb#L136

These are the version of the fog gems I have installed (all the latest as of this writing)
fog-core (2.2.0)
fog-json (1.2.0)
fog-openstack (1.0.10)

The warning doesn't appear to cause any functionality issues.  Everything still works.  Removing that line from the gem eliminates the error, and caused no other side effects that I saw.
I wasn't able to make sense if this provider option is used in newer Openstack versions, or if it's just an extraneous option being passed to fog.

**Comment by Lasering** [comment]
Also happening for Keystone v3 (queens), though I doubt the problem is anything to do with openstack. Most likely fog changed something.

**Comment by ramereth** [comment]
I've been trying to track this down myself by testing on our Rocky-based cluster however whenever I remove that line it stops working. I'll try and take another look soon to figure it out.

**Comment by ramereth** [comment]
@pdohertybcov @Lasering I believe #207 fixes this, Can you please verify?

**Comment by Lasering** [comment]
How can I install kitchen-openstack from that MR?

**Comment by pdohertybcov** [comment]
👍 This worked for me.   I don't see the Warning messages anymore, and everything still appears to work.

**Comment by ramereth** [comment]
> How can I install kitchen-openstack from that MR?

You could do the following:
```
git clone -b misc-fixes https://github.com/test-kitchen/kitchen-openstack.git
cd kitchen-openstack
gem build kitchen-openstack.gemspec
gem install kitchen-openstack*.gem
```
