### ISSUE TITLE
Enhancement: Windows Support

### ISSUE THREAD

**Issue by anthony-cervantes** [test-kitchen/kitchen-openstack#45]
We use chef cookbooks to deploy code to windows servers in openstack. 

Is it possible to get support for windows?

Thanks,
Anthony

**Comment by jmahowald** [comment]
FYI, I should be working on it this week, now that @fnichol has kitchen working well with windows in vagrant

**Comment by kokovoj** [comment]
Great to hear there is movement in this area :)

**Comment by wbirkmaier** [comment]
Yes, great news!

**Comment by jjasghar** [comment]
https://github.com/test-kitchen/kitchen-openstack/pull/92 Will be released.
