### ISSUE TITLE
not able to  find the driver

### ISSUE THREAD

**Issue by suchisubhra** [test-kitchen/kitchen-openstack#72]
I have installed kitchen-openstack thr gem..

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'openstack' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.

looking at log file i see this also. I am not sure these two are related..any help is really appreciated..

E, [2015-01-16T07:05:45.226507 #6234] ERROR -- Kitchen: ------Exception-------
E, [2015-01-16T07:05:45.226602 #6234] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2015-01-16T07:05:45.226639 #6234] ERROR -- Kitchen: Message: Could not load the 'openstack' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
E, [2015-01-16T07:05:45.226674 #6234] ERROR -- Kitchen: ---Nested Exception---
E, [2015-01-16T07:05:45.226709 #6234] ERROR -- Kitchen: Class: Gem::LoadError
E, [2015-01-16T07:05:45.226744 #6234] ERROR -- Kitchen: Message: Unable to activate ohai-7.4.0, because mixlib-shellout-2.0.1 conflicts with mixlib-shellout (~> 1.2)
E, [2015

**Comment by RoboticCheese** [comment]
```
Message: Unable to activate ohai-7.4.0, because mixlib-shellout-2.0.1 conflicts with mixlib-shellout (~> 1.2)
```

Looks like you've got gems with conflicting dependencies on mixlib-shellout. Possibly using Chef 12 (uses mixlib-shellout 2) with pre-1.3 Test Kitchen (uses mixlib-shellout 1)? If so, updating to the latest Test Kitchen might fix it.

This driver doesn't directly depend on mixlib-shellout and isn't pinned to any specific version of ohai, so I don't think the conflict is coming from here. My suggestion would be to always use Bundler--it'll make sure conflicting gems aren't used together and prevent errors like that.
