### ISSUE TITLE
Test Kitchen Openstack doesn't support block storage(volumes)

### ISSUE THREAD

**Issue by LiamHaworth** [test-kitchen/kitchen-openstack#75]
I took notice a little while ago that this drive doesn't support block storage which I required at work, to solve this I added the support to the driver my self, the code can be found on pull req #74

**Comment by osgrob** [comment]
Very cool.  Allows me to add 1 additional volume during kitchen tests.  However, I need to add 4 additional volumes.  Reading the README, I see no way to do that.  Reading the source code, it is not currently supported.

Am I reading everything right?  Any particular reason to limit it to 1 additional block volume?
