### ISSUE TITLE
Config checks in openstack.rb

### ISSUE THREAD

**Issue by darshanvalia** [test-kitchen/kitchen-openstack#82]
In line 46, if possible, please add a check to see whether the private key has been provided or not. I'm getting an error like 

Message: Failed to complete #create action: [undefined method `+' for nil:NilClass]

Which I was able to debug only by looking at the code; the variable driver[:private_key_path] seemed to be missing (since I forgot to provide in config)

**Comment by jjasghar** [comment]
hey @darshanvalia. Can you check if this is a good enough fix for your issue? 

It's just a simple check, but it should help.

**Comment by darshanvalia** [comment]
Yes, good enough. Thanks!
